### ISSUE TITLE
TestCallbackSendCollection failure on some build configuration

### ISSUE THREAD

**Issue by nmm0** [DARMA-tasking/vt#1004] opened 2020-08-25 18:46 UTC
**Describe the bug**
The following tests fail on my machines but not CI:
The following tests FAILED:
                305 - vt:TestCallbackSendCollection.test_callback_send_collection_1_proc_2 (Failed)
                307 - vt:TestCallbackSendCollection.test_callback_send_collection_3_proc_2 (Failed)
                308 - vt:TestCallbackSendCollection.test_callback_send_collection_1_proc_4 (Failed)
                309 - vt:TestCallbackSendCollection.test_callback_send_collection_2_proc_4 (Failed)
                310 - vt:TestCallbackSendCollection.test_callback_send_collection_3_proc_4 (Failed)
Errors while running CTest

**To Reproduce**
1. Example/test/snippet of code that fails
make test
2. Compiler, platform, libraries
llvm 9, mac os x, mpich 3.3.2
3. Run command: number of processors, threading options, etc.
default test configuration

**Expected behavior**
Tests suceeded

**Platform (please complete the following information):**
llvm 9, mpich 3.3.2, mac os x mojave
develop branch

**Additional context**
I'm not sure what configuration is causing this. Will update the issue when I find more (i.e. if it's the compiler or a specific change)

**Comment by lifflander** [comment] 2020-08-25 21:13
@nmm0 I confirm that I can reproduce this on my Mac with clang-9. Haven't tried any other compilers or builds yet.

**Comment by lifflander** [comment] 2020-08-25 21:18
@JacobDomagala @PhilMiller This bug was introduced due to #955 refactoring. We are creating a collection on every node now??

**Comment by lifflander** [comment] 2020-08-25 21:32
This change "fixes" the problem. But we should dig into why that program failed before, creating a collection on every node is a strange thing to do but it shouldn't lead to failure:

```diff
diff --git a/tests/unit/pipe/test_callback_send_collection.extended.cc b/tests/unit/pipe/test_callback_send_collection.extended.cc
index e6873aa1e..0e23c65f1 100644
--- a/tests/unit/pipe/test_callback_send_collection.extended.cc
+++ b/tests/unit/pipe/test_callback_send_collection.extended.cc
@@ -130,7 +130,11 @@ struct TestColMsg : ::vt::CollectionMessage<TestCol> {};
 TEST_F(TestCallbackSendCollection, test_callback_send_collection_1) {
   auto const& this_node = theContext()->getNode();
   auto const& range = Index1D(32);
-  auto proxy = theCollection()->construct<TestCol>(range);
+  vt::CollectionProxy<TestCol, vt::Index1D> proxy;
+
+  if (this_node == 0) {
+    proxy = theCollection()->construct<TestCol>(range);
+  }

   runInEpochCollective([this_node, proxy]{
     if (this_node == 0) {
```

We could also call `constructCollective` instead of `construct` and get rid of the if statement.

**Comment by lifflander** [comment] 2020-08-25 21:33
@PhilMiller We need to be more careful reviewing these changes. Both of us missed this semantic problem in the changed code. The diffs are hard for me to process quickly with these types of changes. It doesn't help that codecov is inserting it's checks in the middle of the diffs.

**Comment by lifflander** [comment] 2020-08-25 21:45
Note: this needs to be fixed in the other two tests also: `test_callback_send_collection_2` `test_callback_send_collection_3`

**Comment by JacobDomagala** [comment] 2020-08-25 22:04
https://github.com/DARMA-tasking/vt/blob/develop/tests/unit/pipe/test_callback_bcast_collection.extended.cc should also be fixed  as well

**Closed** 2020-09-10 23:09 UTC
Labels: type: bug
