### ISSUE TITLE
Test failing on VT develop

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1468] opened 2021-06-08 23:00 UTC
**Describe the bug**
```
13:24:07            Start   74: vt_example:group_collective_16
13:25:15  1713/1718 Test   #74: vt_example:group_collective_16 .............................................................***Timeout  60.08 sec
13:25:15  [32;1mvt[00m: [32mRuntime Initializing:[00m [32mmode: [00m[95msingle-thread per rank[00m
13:25:15  [00m[32;1mvt[00m: [32mProgram: [95mgroup_collective[00m ([95m./group_collective[00m)
13:25:15  [00m[32;1mvt[00m: [32mRunning on: [95m16 nodes[00m
13:25:15  [00m[32;1mvt[00m: [32mMachine Hostname: [95mascic157[00m
13:25:15  [00m[32;1mvt[00m: [32mMPI Version: [95m3[00m.[95m0[00m
13:25:15  [00m[32;1mvt[00m: [32mMPI Max tag: [95m2147483647[00m
13:25:15  [00m[32;1mvt[00m: [32mBuild SHA: [95m48245c5c04da48f5aeef9144cae05e64feb65202[00m
13:25:15  [00m[32;1mvt[00m: [32mBuild Ref: [95m[00m
13:25:15  [00m[32;1mvt[00m: [32mDescription: [95mheads/develop-0-g48245c5c04[00m 
13:25:15  [00m[32;1mvt[00m: [32mCompile-time Features Enabled:[00m
13:25:15  [00m[32;1mvt[00m: 	[95mLoad Balancing for Collections[00m
13:25:15  [32;1mvt[00m: 	[95mMessage priorities[00m
13:25:15  [32;1mvt[00m: 	[95mMemory Pooling[00m
13:25:15  [32;1mvt[00m: 	[95mPerformance analysis diagnostics[00m
13:25:15  [32;1mvt[00m: [32mRuntime Configuration:[00m
13:25:15  [00m[32;1mvt[00m: 	[32mOption:[00m flag [95m--vt_sched_num_progress[00m on: Running MPI progress 2 times each invocation[00m
13:25:15  [00m[32;1mvt[00m: 	[32mOption:[00m flag [95m--vt_sched_progress_han[00m on: Running MPI progress function at least every 0 handler(s) executed[00m
13:25:15  [00m[32;1mvt[00m: 	[32mOption:[00m flag [95m--vt_print_no_progress[00m on: Printing warnings when progress is stalls[00m
13:25:15  [00m[32;1mvt[00m: 	[32mDefault:[00m Printing verbose epoch graphs when hang detected, use [95m--vt_epoch_graph_terse[00m to disable[00m
13:25:15  [00m[32;1mvt[00m: 	[32mOption:[00m flag [95m--vt_epoch_graph_on_hang[00m on: Epoch graph output enabled if hang detected[00m
13:25:15  [00m[32;1mvt[00m: 	[32mDefault:[00m Termination hang detection enabled by default, use [95m--vt_no_detect_hang[00m to disable[00m
13:25:15  [00m[32;1mvt[00m: 	[32mOption:[00m flag [95m--vt_hang_detect[00m on: Printing stall warning every 1024 tree traversals [00m
13:25:15  [00m[32;1mvt[00m: 	[32mDefault:[00m SIGINT signal handling enabled by default, use [95m--vt_no_SIGINT[00m to disable[00m
13:25:15  [00m[32;1mvt[00m: 	[32mDefault:[00m SIGSEGV signal handling enabled by default, use [95m--vt_no_SIGSEGV[00m to disable[00m
13:25:15  [00m[32;1mvt[00m: 	[32mDefault:[00m std::terminate signal handling enabled by default, use [95m--vt_no_terminate[00m to disable[00m
13:25:15  [00m[32;1mvt[00m: 	[32mDefault:[00m Color output enabled, use [95m--vt_no_color[00m to disable[00m
13:25:15  [00m[32;1mvt[00m: 	[32mDefault:[00m Stack dumps enabled by default, use [95m--vt_no_stack[00m to disable[00m
13:25:15  [00m[32;1mvt[00m: 	[32mOption:[00m flag [95m--vt_memory_reporters[00m on: Memory usage checker precedence: mstats,machinfo,selfstat,selfstatm,sbrk,mallinfo,getrusage,ps[00m
13:25:15  [00m[32;1mvt[00m: 	[32mWorking memory reporters:[00m [95mselfstatm,mallinfo,getrusage[00m
13:25:15  [00m[32;1mvt[00m: 	[32mInitial memory usage:[00m [32mselfstatm[00m=[95m9.1875[00m [32mmallinfo[00m=[95m3.26004[00m [32mgetrusage[00m=[95m9.1875[00m (MiB)
13:25:15  [00m[32;1mvt[00m: 	[32mDefault:[00m Memory usage printing disabled, use [95m--vt_print_memory_each_phase[00m to enable[00m
13:25:15  [00m[32;1mvt[00m: 	[32mDefault:[00m Diagnostics are disabled by default, use [95m--vt_diag_enable[00m to enable[00m
13:25:15  [00m[32;1mvt[00m: 	[32mOption:[00m flag [95m--vt_max_mpi_send_size[00m on: Splitting messages greater than 1 GiB[00m
13:25:15  [00m[32;1mvt[00m: 	[32mOption:[00m flag [95m--vt_debug_level[00m on: Debug print mode set to [33mterse[00m[00m
13:25:15  [00m[32;1mvt[00m: [32mPass-through Arguments:[00m
13:25:15  [00m[32;1mvt[00m: 	None. All arguments handled.
13:25:15  [00m[00m0: New group=524287
13:25:15  8: New group=524287
13:25:15  9: New group=524287
13:25:15  10: New group=524287
13:25:15  11: New group=524287
13:25:15  13: New group=524287
13:25:15  14: New group=524287
13:25:15  5: New group=524287
13:25:15  6: New group=524287
13:25:15  1: New group=524287
13:25:15  2: New group=524287
13:25:15  3: New group=524287
13:25:15  4: New group=524287
13:25:15  7: New group=524287
13:25:15  12: New group=524287
13:25:15  15: New group=524287
13:25:15  0: Group is created: group=7ffff, in_group=false, root=13, is_default_group=false
13:25:15  4: Group is created: group=7ffff, in_group=false, root=13, is_default_group=false
13:25:15  6: Group is created: group=7ffff, in_group=false, root=13, is_default_group=false
13:25:15  2: Group is created: group=7ffff, in_group=false, root=13, is_default_group=false
13:25:15  14: Group is created: group=7ffff, in_group=false, root=13, is_default_group=false
13:25:15  8: Group is created: group=7ffff, in_group=false, root=13, is_default_group=false
13:25:15  10: Group is created: group=7ffff, in_group=false, root=13, is_default_group=false
13:25:15  12: Group is created: group=7ffff, in_group=false, root=13, is_default_group=false
13:25:15  1: Group is created: group=7ffff, in_group=true, root=13, is_default_group=false
13:25:15  5: Group is created: group=7ffff, in_group=true, root=13, is_default_group=false
13:25:15  9: Group is created: group=7ffff, in_group=true, root=13, is_default_group=false
13:25:15  9: Hello from group handler
13:25:15  11: Group is created: group=7ffff, in_group=true, root=13, is_default_group=false
13:25:15  13: Group is created: group=7ffff, in_group=true, root=13, is_default_group=false
13:25:15  3: Group is created: group=7ffff, in_group=true, root=13, is_default_group=false
13:25:15  3: Hello from group handler
13:25:15  15: Group is created: group=7ffff, in_group=true, root=13, is_default_group=false
13:25:15  15: Hello from group handler
13:25:15  7: Group is created: group=7ffff, in_group=true, root=13, is_default_group=false
13:25:15  7: Hello from group handler
13:25:15  11: Hello from group handler
13:25:15  13: Hello from group handler
13:25:15  5: Hello from group handler
13:25:15  1: Hello from group handler
13:25:15  final value=8
13:25:15  [32;1mvt[00m: [32mTotal collective epochs processed:[00m [95m0[00m
13:25:15  [32;1mvt[00m: [32mTotal work units processed:[00m [95m411[00m
13:25:15  [32;1mvt[00m: [32mRuntime Finalizing[00m[00m
13:25:15  
13:25:15            Start  104: vt_example:hello_world_collection_staged_insert_16
13:25:15  1714/1718 Test  #104: vt_example:hello_world_collection_staged_insert_16 .........................................   Passed    0.47 sec
13:25:15            Start   38: vt_example:jacobi2d_vt_16
13:25:15  1715/1718 Test   #38: vt_example:jacobi2d_vt_16 ..................................................................   Passed    0.52 sec
13:25:15            Start   68: vt_example:group_rooted_16
13:25:15  1716/1718 Test   #68: vt_example:group_rooted_16 .................................................................   Passed    0.53 sec
13:25:15            Start   62: vt_example:transpose_16
13:25:15  1717/1718 Test   #62: vt_example:transpose_16 ....................................................................   Passed    0.38 sec
13:25:15            Start   92: vt_example:hello_world_collection_16
13:25:15  1718/1718 Test   #92: vt_example:hello_world_collection_16 .......................................................   Passed    0.42 sec
13:25:15  
13:25:15  99% tests passed, 1 tests failed out of 1718
13:25:15  
13:25:15  Label Time Summary:
13:25:15  SLOW    = 3598.25 sec*proc (77 tests)
13:25:15  
13:25:15  Total Test time (real) = 975.29 sec
13:25:15  
13:25:15  The following tests FAILED:
13:25:15  	 74 - vt_example:group_collective_16 (Timeout)
13:25:15  Errors while running CTest
```

**Comment by cz4rs** [comment] 2021-09-07 13:19
Could not reproduce:
```
 ctest -R vt_example:group_collective --output-on-failure --repeat-until-fail 1000
(...)
100% tests passed, 0 tests failed out of 3
```

Closing.

**Closed by cz4rs** 2021-09-07 13:19 UTC
Labels: type: bug
