### ISSUE TITLE
sprintf warning on macOS

### ISSUE THREAD

**Issue by stmcgovern** [DARMA-tasking/vt#2125] opened 2023-03-29 19:23 UTC
**What Needs to be Done?**

When building on mac I am seeing a warning of `'sprintf' is deprecated`
It recommends using `snprintf` .

Also might be useful to enable `-Werror` in macos builds.

**Comment by nlslatt** [comment] 2023-10-03 16:56
Duplicate of https://github.com/DARMA-tasking/magistrate/issues/311

**Comment by nlslatt** [comment] 2023-10-24 15:51
@thearusable There are two more uses of `sprintf` in vt that we need fixed. Thanks!

**Closed** 2023-11-07 20:03 UTC
Labels: type: task
