### ISSUE TITLE
Tutorial failed in group construction code after multiple runs

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1396] opened 2021-04-21 01:54 UTC
**What Needs to be Done?**

I'm running like this `ctest --rerun-failed --output-on-failure --repeat-until-fail 100`. Might be related to the closed issue #1006, merged PR #1325

```
0: triggering active message callback bcast
msgHandlerGroupA: triggered on node=5
6: triggering active message callback bcast
2: triggering active message callback bcast
5: triggering active message callback bcast
vt: [0] ------------------------------------------------------------------------------------------------------------------------
vt: [0] ------------------------------------------- Runtime Error: System Aborting! --------------------------------------------
vt: [0] ------------------------------------------------ Fatal Error on Node 0 -------------------------------------------------
vt: [0] ------------------------------------------------------------------------------------------------------------------------
vt: [0]
vt: [0]              Reason: Must have valid op
vt: [0]    Assertion failed: (op_id != no_op_id)
vt: [0]                Node: 0
vt: [0]           Num Nodes: 8
vt: [0]                File: /vt/src/vt/group/collective/group_info_collective.cc
vt: [0]                Line: 606
vt: [0]            Function: upHan
vt: [0]                Code: 1
vt: [0]           Build SHA: eda77a621097a2c9c68b93b6a50417a3162192de
vt: [0]           Build Ref: refs/heads/1362-eti-for-collections
vt: [0]         Description: heads/1362-eti-for-collections-0-geda77a6210
vt: [0]            GIT Repo: *dirty*
vt: [0]            Hostname: aa94d042ec11
vt: [0]
vt: [0] ------------------------------------------------------------------------------------------------------------------------
vt: [0] -------------------------------------------- Dump Stack Backtrace on Node 0 --------------------------------------------
vt: [0] ------------------------------------------------------------------------------------------------------------------------
vt: [0] 0   18  0x55e9d03672af vt::debug::stack::dumpStack[abi:cxx11](int) + 63
vt: [0] 1   18  0x55e9cfc3d81a vt::runtime::Runtime::output(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, bool, bool) + 3146
vt: [0] 2   18  0x55e9d0346ec7 vt::CollectiveAnyOps<(vt::runtime::eRuntimeInstance)0>::output(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, bool, bool, bool) + 135
vt: [0] 3   18  0x55e9d0332554 vt::output(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, bool, bool, bool) + 100
vt: [0] 4   18  0x55e9d02eb019 ./tutorial(+0xeeb019) [0x55e9d02eb019] + 0
vt: [0] 5   18  0x55e9d02ece83 vt::group::InfoColl::upHan(vt::group::GroupCollectiveInfoMsg<vt::group::GroupMsg<vt::messaging::ActiveMsg<vt::messaging::EpochTagActiveEnvelope> > >*) + 419
vt: [0] 6   18  0x55e9cf91eb7b vt::sched::ThreadAction::runFnImpl(fcontext_transfer_t) + 91
vt: [0] 7   18  0x55e9d03bf6db make_fcontext + 27
vt: [0] ------------------------------------------------------------------------------------------------------------------------
vt: [0] ------------------------------------------- Runtime Error: System Aborting! --------------------------------------------
vt: [0] ------------------------------------------------ Fatal Error on Node 0 -------------------------------------------------
vt: [0] ------------------------------------------------------------------------------------------------------------------------
vt: [0]
vt: [0] Message: Assertion Failed
vt: [0]
vt: [0] ------------------------------------------------------------------------------------------------------------------------
vt: [0] -------------------------------------------- Dump Stack Backtrace on Node 0 --------------------------------------------
vt: [0] ------------------------------------------------------------------------------------------------------------------------
vt: [0] 0   18  0x55e9d03672af vt::debug::stack::dumpStack[abi:cxx11](int) + 63
vt: [0] 1   18  0x55e9cfc3d81a vt::runtime::Runtime::output(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, bool, bool) + 3146
vt: [0] 2   18  0x55e9cfc3dc21 vt::runtime::Runtime::abort(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int) + 97
vt: [0] 3   18  0x55e9d03453f5 vt::CollectiveAnyOps<(vt::runtime::eRuntimeInstance)0>::abort(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int) + 85
vt: [0] 4   18  0x55e9d0330e9f vt::abort(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int) + 63
vt: [0] 5   18  0x55e9d0346f0d vt::CollectiveAnyOps<(vt::runtime::eRuntimeInstance)0>::output(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, bool, bool, bool) + 205
vt: [0] 6   18  0x55e9d0332554 vt::output(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, bool, bool, bool) + 100
vt: [0] 7   18  0x55e9d02eb019 ./tutorial(+0xeeb019) [0x55e9d02eb019] + 0
vt: [0] 8   18  0x55e9d02ece83 vt::group::InfoColl::upHan(vt::group::GroupCollectiveInfoMsg<vt::group::GroupMsg<vt::messaging::ActiveMsg<vt::messaging::EpochTagActiveEnvelope> > >*) + 419
vt: [0] 9   18  0x55e9cf91eb7b vt::sched::ThreadAction::runFnImpl(fcontext_transfer_t) + 91
vt: [0] 10  18  0x55e9d03bf6db make_fcontext + 27
```

**Comment by cz4rs** [comment] 2021-09-07 12:58
This seems to be fixed in another issue, could not reproduce:

```
ctest -R tutorial --output-on-failure --repeat-until-fail 1000
(...)
100% tests passed, 0 tests failed out of 3
```

**Closed by cz4rs** 2021-09-07 12:58 UTC
Labels: type: task

**Comment by lifflander** [comment] 2021-09-07 13:14
I think this bug is fixed by https://github.com/DARMA-tasking/vt/pull/1511
